---
services:
  paper-frontend:
    build:
      context: ${BASE_DIR}
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        - API_URL_SERVER=${API_URL_SERVER:-http://paper-backend:8000}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your_secret_key_here}
        - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    env_file:
      - $BASE_DIR/.env
    restart: always
    networks:
      - paper-summary-network

networks:
  paper-summary-network:
