---
services:
  paper-frontend:
    build:
      context: ${BASE_DIR}
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - $BASE_DIR/.env
    restart: always
    networks:
      - paper-summary-network

networks:
  paper-summary-network:
