---
services:
  paper-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - paper-summary-network
    depends_on:
      - paper-db
      - paper-crawler

networks:
  paper-summary-network:

