---
services:
  paper-backend:
    build:
      context: $BASE_DIR
      dockerfile: Dockerfile
    env_file:
      - $BASE_DIR/.env
    ports:
      - "8000:8000"
    networks:
      - paper-summary-network
    depends_on:
      - paper-db

networks:
  paper-summary-network:

