---
services:
  paper-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - paper-backend
    restart: always
    networks:
      - paper-summary-network

networks:
  paper-summary-network:
