---
services:
  paper-crawler:
    build:
      context: $BASE_DIR
      dockerfile: Dockerfile
    env_file:
      - $BASE_DIR/.env
    networks:
      - paper-summary-network
    depends_on:
      - paper-db

networks:
  paper-summary-network:
