---
services:
  paper-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - paper-summary-network
    depends_on:
      - paper-db

networks:
  paper-summary-network:
